name: Deploy to Cloudflare Pages

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        strategy:
            matrix:
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node-version: [18.x]
                include:
                    - projectName: 'ematchi'
                      directory: 'build'
                    - projectName: 'rock-paper-scissors-lizard-spock'
                      directory: 'build'
                    - projectName: 'svelteflix'
                      directory: '.svelte-kit/cloudflare'
                    - projectName: 'privelte'
                      directory: '.svelte-kit/cloudflare'
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Deploy
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ matrix.projectName }}
                  directory: apps/${{ matrix.projectName }}/${{ matrix.directory }}
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
