name: Deploy to Cloudflare Pages

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        strategy:
            matrix:
                include:
                    - projectName: 'ematchi'
                    - projectName: 'rock-paper-scissors-lizard-spock'
                    - projectName: 'svelteflix'
                    - projectName: 'privelte'
        # To use Turborepo Remote Caching, set the following environment variables for the job.
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build --filter ${{ matrix.projectName }}

            - name: Deploy
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ matrix.projectName }}
                  directory: apps/${{ matrix.projectName }}/.svelte-kit/cloudflare
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
