on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        strategy:
            matrix:
                include:
                    - projectName: 'ematchi'
                      directory: 'apps/ematchi/build'
                    - projectName: 'rock-paper-scissors-lizard-spock'
                      directory: 'apps/rock-paper-scissors-lizard-spock/build'
                    - projectName: 'svelteflix'
                      directory: 'apps/svelteflix/.svelte-kit/cloudflare'
                    - projectName: 'privelte'
                      directory: 'apps/privelte/.svelte-kit/cloudflare'
        # To use Turborepo Remote Caching, set the following environment variables for the job.
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Setup Node.js environment
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm build

            - name: Publish
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ matrix.projectName }}
                  directory: ${{ matrix.directory }}
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
